### ISSUE TITLE
Old BFRES Files?

### ISSUE THREAD

**Issue by MichaelHinrichs** [KillzXGaming/BfresLibrary#6]
I saw in a comment in bfres library that “very old versions have no counts and is mostly unkown atm”. This is on an else statement for files below version 2.4.0.0. But I have found a couple of files that are older than that, which do have file counters. They are versions 1.0.0.5, and 1.1.0.7. What are some examples of bfres without file counters? How old is their version number?

**Comment by KillzXGaming** [comment]
What uses such old bfres? Oldest version I've seen was around 2.0 but I didn't really try to support it since no games use such old versions (launch titles are around 3.0).

**Comment by MichaelHinrichs** [comment]
Common\actor\P_rcha\P_rcha.szs\P_rcha.sarc\P_rcha.bfres from New Super Mario Bros U is 1.0.0.5.
CMCmn\enemy\tuyukusa.szs\tuyukusa.sarc\tuyukusa.bfres from Pikmin 3 is 1.1.0.7

I was able to find pages for bolt of them on tcrf, and apparently they are both unused in their games. 
https://tcrf.net/New_Super_Mario_Bros._U#Unused_Animations
https://tcrf.net/Pikmin_3#Misc.

They both have 9 index groups references instead of 12. They both contain skeleton animations, and P_rcha has color animation, but that's all that either contains.

**Comment by MichaelHinrichs** [comment]
So like, where can these version 2 bfres files be found?

**Comment by MichaelHinrichs** [comment]
Ok, Thank you.
